# Generated by Django 6.0.6 on 2026-07-03 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('llm_facade', 'LLM Facade'), ('translate', 'Translate'), ('other', 'Other')], db_index=True, max_length=32)),
                ('model', models.CharField(max_length=128)),
                ('model_size', models.CharField(max_length=16)),
                ('prompt', models.TextField()),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('timeout', 'Timeout'), ('error', 'Error')], db_index=True, max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('thinking_tokens', models.IntegerField(blank=True, null=True)),
                ('cache_read_tokens', models.IntegerField(blank=True, null=True)),
                ('cache_write_tokens', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'agent_prompt_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', '-created_at'], name='agent_source_created_idx')],
            },
        ),
    ]
