# Generated by Django 6.0.6 on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_promptlog_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptlog',
            name='source',
            field=models.CharField(choices=[('llm_facade', 'LLM Facade'), ('translate', 'Translate'), ('transcribe', 'Transcribe'), ('summarize', 'Summarize'), ('generate_image', 'Generate Image'), ('other', 'Other')], db_index=True, max_length=32),
        ),
    ]
