# Generated by Django 6.0.7 on 2026-08-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_promptlog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptlog',
            name='audio_duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptlog',
            name='cost_basis',
            field=models.CharField(blank=True, choices=[('provider_ticks', 'Reported by the provider'), ('pricing_estimate', 'Estimated from the rate card'), ('unpriced', 'No rate card — cost unknown')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='promptlog',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='promptlog',
            name='workspace_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='promptlog',
            index=models.Index(fields=['workspace_id', '-created_at'], name='agent_ws_created_idx'),
        ),
    ]
